name : Release

on :
  push :
    tags :
      - 'v*.*.*'

jobs :
  publish-release :
    runs-on : ubuntu-latest
    if : github.repository == 'square/anvil'
    timeout-minutes : 25

    steps :
      - uses : actions/checkout@v2
      - uses : gradle/wrapper-validation-action@v1
      - uses : actions/setup-java@v2
        with :
          distribution : 'temurin'
          java-version : '11'
          check-latest : true

      # TODO: Revert release changes when we drop support for 1.7
      - name : Publish Release 1.7
        run : ./gradlew clean publish --no-build-cache --no-daemon --stacktrace --no-parallel -Psquare.kotlinVersion=1.7.20 && cd gradle-plugin && ./gradlew clean publish --no-build-cache --no-daemon --stacktrace -Psquare.kotlinVersion=1.7.20 && cd ..
        env :
          ORG_GRADLE_PROJECT_mavenCentralUsername : ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword : ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey : ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword : ''

      - name : Publish Release 1.8
        run : ./gradlew clean publish --no-build-cache --no-daemon --stacktrace --no-parallel -Psquare.kotlinVersion=1.8.0-RC -PVERSION_NAME=2.4.4-1-8-0-RC && cd gradle-plugin && ./gradlew clean publish --no-build-cache --no-daemon --stacktrace -Psquare.kotlinVersion=1.8.0-RC -PVERSION_NAME=2.4.4-1-8-0-RC && cd ..
        env :
          ORG_GRADLE_PROJECT_mavenCentralUsername : ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword : ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey : ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword : ''

      - name : Extract release notes
        id : release_notes
        uses : ffurrer2/extract-release-notes@v1

      - name : Create release
        uses : softprops/action-gh-release@v1
        with :
          body : ${{ steps.release_notes.outputs.release_notes }}
        env :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
